#修改默认端口
server:
  port: 8081

#配置数据源的信息
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/views

#配置自定义的变量
name: 张三


#对象的声明
student:
  sname: Mike
  ssex: 男
  sage: 16

#数组
persons:
  - pname: 李四
    age: 18
  - pname: Lucy
    age: 20

#注册映射文件
mybatis:
  type-aliases-package: com.jxd.emp.model  #这是设置实体类的别名
  mapper-locations: classpath:mapper/*.xml


beetl:
  #当确定前台文件的目录位置后，后缀设置可以省略
  #suffix: html       #将beetl模板文件后缀定义为html
  #改变beetl得分隔符
  DELIMITER_STATEMENT_START: \@
  DELIMITER_STATEMENT_END: null
